name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install build essentials
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: compile
      run: gcc -o copier copier.c
    - name: run tests
      run: ./copier source.c destination.c
